### ISSUE TITLE
Probability LSA

### ISSUE THREAD

**Issue by hbthien** [fozziethebeat/S-Space#65]
Dear all,

Does S-Space support for probability LSA (PLSA)? If yes, could you please tell me which file I should consider and test this method?

Thanks a lot.

**Comment by davidjurgens** [comment]
Hi,

  At the moment, S-Space does not have PLSA implemented.

  Thanks,
  David

**Comment by hbthien** [comment]
Hi,
Thank you.
However, I got a problem with the localisation too. I already mentioned this problem in the issue "17errors..." please tell me how to fix it.

**Comment by hbthien** [comment]
Hi, I solved this error. It's a truely localisation problem.
